services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  api:
    build:
      context: ./ecommerce-api
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - postgres
      - mongodb
    restart: unless-stopped
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/ecommerce
      - SPRING_R2DBC_USERNAME=admin
      - SPRING_R2DBC_PASSWORD=admin123
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin123@mongodb:27017/ecommerce?authSource=admin

  frontend:
    build:
      context: ./ecommerce-front
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - api
    ports:
      - "4230:80"
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
